export const products = [
  {
    id: 1,
    name: "Laptop",
    price: 999.99,
    description: "A high-end laptop",
    available: true,
    stock: 5,
  },
  {
    id: 2,
    name: "Headphones",
    price: 199.99,
    description: "Noise-cancelling headphones",
    available: true,
    stock: 10,
  },
  {
    id: 3,
    name: "Smartphone",
    price: 799.99,
    description: "A flagship smartphone",
    available: true,
    stock: 3,
  },
  {
    id: 4,
    name: "Keyboard",
    price: 49.99,
    description: "Mechanical keyboard",
    available: true,
    stock: 15,
  },
  {
    id: 5,
    name: "Mouse",
    price: 25.99,
    description: "Wireless mouse",
    available: true,
    stock: 20,
  },
  {
    id: 6,
    name: "Monitor",
    price: 299.99,
    description: "4K monitor",
    available: false,
    stock: 0,
  },
  {
    id: 7,
    name: "Tablet",
    price: 499.99,
    description: "A lightweight tablet",
    available: true,
    stock: 7,
  },
  {
    id: 8,
    name: "Smartwatch",
    price: 199.99,
    description: "Fitness tracker smartwatch",
    available: true,
    stock: 12,
  },
  {
    id: 9,
    name: "Printer",
    price: 89.99,
    description: "Wireless inkjet printer",
    available: true,
    stock: 8,
  },
  {
    id: 10,
    name: "External Hard Drive",
    price: 69.99,
    description: "1TB external hard drive",
    available: true,
    stock: 9,
  },
];
